/**
 * Asset manifest — typed path registry for portraits, reference art,
 * UI battle chrome, icon assets, and battle animation frame folders.
 *
 * For battle animation frame lists, import CHARACTERS_MANIFEST from
 * '../generated/characters-manifest' — that file is auto-generated by
 * `npm run gen:manifest` and is always up to date with the actual PNGs
 * on disk.
 *
 * Paths are relative to the public/ directory (no leading slash) so Phaser
 * resolves them from the Vite public root at runtime.
 */

const M = 'assets/monari';
const C = 'assets/characters';
const UI = 'assets/ui';

export type MonariGender = 'male' | 'female' | 'unknown';

export interface VisualAssetPaths {
  id: string;
  portrait: string;
  icon: string;
  reference: string;
  fallbackKey: string;
}

export type MonariPaths = VisualAssetPaths;
export type CharacterPaths = VisualAssetPaths;

export interface BattleUiFramePaths {
  panelMonariLeft: string;
  panelMonariRight: string;
  turnBadge: string;
  soulbondBar: string;
  soulsyncBar: string;
}

export interface BattleUiButtonPaths {
  fight: string;
  bag: string;
  bond: string;
  run: string;
}

function monari(id: string, reference = 'full_body.png'): MonariPaths {
  return {
    id,
    portrait: `${M}/${id}/portraits/neutral.png`,
    icon: `${M}/${id}/portraits/icon.png`,
    reference: `${M}/${id}/reference/${reference}`,
    fallbackKey: `generated_monari_${id}`,
  };
}

function character(id: string, reference = 'full_body.png'): CharacterPaths {
  return {
    id,
    portrait: `${C}/${id}/portraits/neutral.png`,
    icon: `${C}/${id}/portraits/icon.png`,
    reference: `${C}/${id}/reference/${reference}`,
    fallbackKey: `generated_character_${id}`,
  };
}

export const MONARI_PATHS: Record<string, MonariPaths> = {
  flarepaw: monari('flarepaw', 'flarepaw_sheet.png'),
  droplet: monari('droplet', 'fullbody.png'),
  umbrelette: monari('umbrelette', 'fullbody.png'),
  uvee: monari('uvee', 'fullbody.png'),
  sproutodon: monari('sproutodon', 'fullbody.png'),
  umbravine: monari('umbravine', 'fullbody.png'),
};

export const CHARACTER_PATHS: Record<string, CharacterPaths> = {
  player: character('player', 'fullbody.png'),
  renzo: character('renzo', 'fullbody.png'),
  amari: character('amari', 'fullbody.png'),
  erix: character('erix', 'fullbody.png'),
  warren_ellis: character('warren_ellis', 'fullbody.png'),
};

export const BATTLE_UI_FRAMES: BattleUiFramePaths = {
  panelMonariLeft: `${UI}/battle/frames/panel_monari_left_empty.png`,
  panelMonariRight: `${UI}/battle/frames/panel_monari_right_empty.png`,
  turnBadge: `${UI}/battle/frames/turn_badge_empty.png`,
  soulbondBar: `${UI}/battle/frames/soulbond_bar_empty.png`,
  soulsyncBar: `${UI}/battle/frames/soulsync_bar_empty.png`,
};

export const BATTLE_UI_BUTTONS: BattleUiButtonPaths = {
  fight: `${UI}/battle/buttons/btn_fight.png`,
  bag: `${UI}/battle/buttons/btn_bag.png`,
  bond: `${UI}/battle/buttons/btn_bond.png`,
  run: `${UI}/battle/buttons/btn_run.png`,
};

const ELEMENT_ICON_FILE: Record<string, string> = {
  ember: 'fire',
  fire: 'fire',
  aqua: 'water',
  water: 'water',
  flora: 'flora',
  terra: 'stone',
  earth: 'stone',
  stone: 'stone',
  gale: 'wind',
  wind: 'wind',
  bolt: 'thunder',
  lightning: 'thunder',
  thunder: 'thunder',
  steel: 'steel',
  light: 'light',
  shadow: 'dark',
  dark: 'dark',
  aether: 'aether',
  ice: 'ice',
  neutral: 'neutral',
  none: 'neutral',
};

export function getMonariVisualPaths(id: string): MonariPaths {
  return MONARI_PATHS[id] ?? monari(id);
}

export function getCharacterVisualPaths(id: string): CharacterPaths {
  return CHARACTER_PATHS[id] ?? character(id);
}

export function visualCandidateKeys(kind: 'monari' | 'character', id: string): string[] {
  return [`${kind}_${id}_portrait`, `${kind}_${id}_icon`, `${kind}_${id}_reference`];
}

export function visualCandidates(paths: VisualAssetPaths): string[] {
  return [paths.portrait, paths.icon, paths.reference];
}

export function battleUiFrameKey(key: keyof BattleUiFramePaths): string {
  return `ui_battle_frame_${key}`;
}

export function battleUiButtonKey(key: keyof BattleUiButtonPaths): string {
  return `ui_battle_button_${key}`;
}

export function getElementIconPath(element?: string): string {
  const file = ELEMENT_ICON_FILE[(element ?? 'neutral').toLowerCase()] ?? 'neutral';
  return `${UI}/elements/${file}.png`;
}

export function elementIconKey(element?: string): string {
  const file = ELEMENT_ICON_FILE[(element ?? 'neutral').toLowerCase()] ?? 'neutral';
  return `ui_element_${file}`;
}

export function getGenderIconPath(gender?: string): string {
  const normalized: MonariGender = gender === 'male' || gender === 'female' ? gender : 'unknown';
  return `${UI}/icons/gender_${normalized}.png`;
}

export function genderIconKey(gender?: string): string {
  const normalized: MonariGender = gender === 'male' || gender === 'female' ? gender : 'unknown';
  return `ui_gender_${normalized}`;
}

export function getMonariBattleFramePath(monariId: string, base: string, folder: string, stem: string): string {
  const battleRoot = monariId === 'flarepaw' ? `${base}/battle` : base;
  return `${battleRoot}/${folder}/${stem}.png`;
}

export function getMonariBattleFolderPath(monariId: string): string {
  return `${M}/${monariId}${monariId === 'flarepaw' ? '/battle' : ''}`;
}

export function getMonariOverworldPath(monariId: string): string {
  return `${M}/${monariId}/overworld`;
}
