/**
 * Asset manifest — typed path registry for portraits, reference art,
 * and overworld assets.
 *
 * For battle animation frame lists, import CHARACTERS_MANIFEST from
 * '../generated/characters-manifest' — that file is auto-generated by
 * `npm run gen:manifest` and is always up to date with the actual PNGs
 * on disk.
 *
 * Paths are relative to the public/ directory (no leading slash).
 */

const M = 'assets/monari';
const C = 'assets/characters';

export interface VisualAssetPaths {
  id: string;
  portrait: string;
  icon: string;
  reference: string;
  fallbackKey: string;
}

export type MonariPaths = VisualAssetPaths;
export type CharacterPaths = VisualAssetPaths;

function monari(id: string, reference = 'full_body.png'): MonariPaths {
  return {
    id,
    portrait: `${M}/${id}/portraits/neutral.png`,
    icon: `${M}/${id}/portraits/icon.png`,
    reference: `${M}/${id}/reference/${reference}`,
    fallbackKey: `generated_monari_${id}`,
  };
}

function character(id: string, reference = 'full_body.png'): CharacterPaths {
  return {
    id,
    portrait: `${C}/${id}/portraits/neutral.png`,
    icon: `${C}/${id}/portraits/icon.png`,
    reference: `${C}/${id}/reference/${reference}`,
    fallbackKey: `generated_character_${id}`,
  };
}

export const MONARI_PATHS: Record<string, MonariPaths> = {
  flarepaw: monari('flarepaw', 'neutral.png'),
  droplet: monari('droplet', 'fullbody.png'),
  umbrelette: monari('umbrelette', 'fullbody.png'),
  uvee: monari('uvee', 'fullbody.png'),
  sproutodon: monari('sproutodon', 'fullbody.png'),
  umbravine: monari('umbravine', 'fullbody.png'),
};

export const CHARACTER_PATHS: Record<string, CharacterPaths> = {
  player: character('player', 'fullbody.png'),
  renzo: character('renzo', 'fullbody.png'),
  amari: character('amari', 'fullbody.png'),
  erix: character('erix', 'fullbody.png'),
  warren_ellis: character('warren_ellis', 'fullbody.png'),
};

export function getMonariVisualPaths(id: string): MonariPaths {
  return MONARI_PATHS[id] ?? monari(id);
}

export function getCharacterVisualPaths(id: string): CharacterPaths {
  return CHARACTER_PATHS[id] ?? character(id);
}

export function visualCandidateKeys(kind: 'monari' | 'character', id: string): string[] {
  return [`${kind}_${id}_portrait`, `${kind}_${id}_icon`, `${kind}_${id}_reference`];
}

export function visualCandidates(paths: VisualAssetPaths): string[] {
  return [paths.portrait, paths.icon, paths.reference];
}
