/**
 * Asset manifest — typed path registry for portraits, reference art,
 * overworld assets, battle animation folders, and UI HUD art.
 *
 * For battle animation frame lists, import CHARACTERS_MANIFEST from
 * '../generated/characters-manifest' — that file is auto-generated by
 * `npm run gen:manifest` and is always up to date with the actual PNGs
 * on disk.
 *
 * Paths are relative to the public/ directory (no leading slash).
 */

const M = 'assets/monari';
const C = 'assets/characters';

export interface VisualAssetPaths {
  id: string;
  portrait: string;
  icon: string;
  reference: string;
  fallbackKey: string;
}

export interface MonariPaths extends VisualAssetPaths {
  battleRoot: string;
  overworldRoot: string;
}
export type CharacterPaths = VisualAssetPaths;

export type MonariGenderAsset = 'male' | 'female' | 'unknown';

function monari(id: string, reference = 'full_body.png'): MonariPaths {
  return {
    id,
    portrait: `${M}/${id}/portraits/neutral.png`,
    icon: `${M}/${id}/portraits/icon.png`,
    reference: `${M}/${id}/reference/${reference}`,
    fallbackKey: `generated_monari_${id}`,
    battleRoot: `${M}/${id}/battle`,
    overworldRoot: `${M}/${id}/overworld`,
  };
}

function character(id: string, reference = 'full_body.png'): CharacterPaths {
  return {
    id,
    portrait: `${C}/${id}/portraits/neutral.png`,
    icon: `${C}/${id}/portraits/icon.png`,
    reference: `${C}/${id}/reference/${reference}`,
    fallbackKey: `generated_character_${id}`,
  };
}

export const MONARI_PATHS: Record<string, MonariPaths> = {
  flarepaw: monari('flarepaw', 'neutral.png'),
  droplet: monari('droplet', 'fullbody.png'),
  umbrelette: monari('umbrelette', 'fullbody.png'),
  uvee: monari('uvee', 'fullbody.png'),
  sproutodon: monari('sproutodon', 'fullbody.png'),
  umbravine: monari('umbravine', 'fullbody.png'),
};

export const CHARACTER_PATHS: Record<string, CharacterPaths> = {
  player: character('player', 'fullbody.png'),
  renzo: character('renzo', 'fullbody.png'),
  amari: character('amari', 'fullbody.png'),
  erix: character('erix', 'fullbody.png'),
  warren_ellis: character('warren_ellis', 'fullbody.png'),
};

export function getMonariVisualPaths(id: string): MonariPaths {
  return MONARI_PATHS[id] ?? monari(id);
}

export function getCharacterVisualPaths(id: string): CharacterPaths {
  return CHARACTER_PATHS[id] ?? character(id);
}

export function visualCandidateKeys(kind: 'monari' | 'character', id: string): string[] {
  return [`${kind}_${id}_portrait`, `${kind}_${id}_icon`, `${kind}_${id}_reference`];
}

export function visualCandidates(paths: VisualAssetPaths): string[] {
  return [paths.portrait, paths.icon, paths.reference];
}


const UI = 'assets/ui';
const UI_ASSET_VERSION = 'v=3';

function uiAsset(path: string): string {
  return `${path}?${UI_ASSET_VERSION}`;
}

export const BATTLE_UI_FRAMES = {
  playerPanel: uiAsset(`${UI}/battle/frames/panel_monari_left_empty.png`),
  enemyPanel: uiAsset(`${UI}/battle/frames/panel_monari_right_empty.png`),
  turnBadge: uiAsset(`${UI}/battle/frames/turn_badge_empty.png`),
  soulbondBar: uiAsset(`${UI}/battle/frames/soulbond_bar_empty.png`),
  soulsyncBar: uiAsset(`${UI}/battle/frames/soulsync_bar_empty.png`),
} as const;


export const BATTLE_UI_FRAME_FALLBACKS = {
  playerPanel: uiAsset(`${UI}/battle/frames/  panel_monari_left_empty.png`),
  enemyPanel: uiAsset(`${UI}/battle/frames/  panel_monari_right_empty.png`),
  turnBadge: BATTLE_UI_FRAMES.turnBadge,
  soulbondBar: BATTLE_UI_FRAMES.soulsyncBar,
  soulsyncBar: BATTLE_UI_FRAMES.soulsyncBar,
} as const;

export const BATTLE_UI_BUTTONS = {
  fight: uiAsset(`${UI}/battle/buttons/btn_fight.png`),
  bag: uiAsset(`${UI}/battle/buttons/btn_bag.png`),
  capture: uiAsset(`${UI}/battle/buttons/btn_bond.png`),
  run: uiAsset(`${UI}/battle/buttons/btn_run.png`),
} as const;

export function getElementIconPath(element?: string): string {
  const normalized = (element ?? 'neutral').toLowerCase();
  const supported = new Set(['fire', 'water', 'flora', 'wind', 'thunder', 'stone', 'steel', 'light', 'dark', 'aether', 'ice', 'neutral']);
  return uiAsset(`${UI}/elements/${supported.has(normalized) ? normalized : 'neutral'}.png`);
}

export function getGenderIconPath(gender?: string): string {
  const normalized = (gender ?? 'unknown').toLowerCase();
  const safe: MonariGenderAsset = normalized === 'male' || normalized === 'female' ? normalized : 'unknown';
  return uiAsset(`${UI}/icons/gender_${safe}.png`);
}

export function getMonariBattleAnimationFolder(id: string, folder: string): string {
  return `${getMonariVisualPaths(id).battleRoot}/${folder}`;
}

export function getMonariOverworldRoot(id: string): string {
  return getMonariVisualPaths(id).overworldRoot;
}
